#TRASH #2 WORKFLOW

#name: My-Trash  

#env:
  # C_SIZE  : "20cm"
   B_WEIGHT: "50KG"
on: 
  push: 
    branches:
       - main
       
       
jobs:
  my_ass:
      runs-on: ubuntu-latest
      
      steps:
        - name: Print Hey
          run : echo "Hey NIGGA"
          
        - name: Clone The Repo
          uses: actions/checkout@v1
            
        - name: List the files
          run : ls -la
            
  
  my_balls:
      runs-on: ubuntu-latest
      needs: [my_ass]
        
      steps:
        - name: Print Hey
          run : echo "Hey My Balls!!"
          
        - name: Print Cock Size and Balls Weight
 #         run : |
  #        echo "My cock is ${{ env.C_SIZE }}"
 #           echo "My balls weight ${{ env.B_WEIGHT }}"
            
 
